# search in google as "aws eks targetgroupbinding" -->click on github.io
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: frontend
spec:
  serviceRef:
    name: frontend # route traffic to the frontend
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:695862934667:targetgroup/expense-dev/f8439ec18b85cd1f 
  # aws --> ec2 --> target groups --> copy the target group  arn